<?php
/*
 * @author Michael Mifsud <info@tropotek.com>
 * @link http://www.tropotek.com/
 * @license Copyright 2007 Michael Mifsud
 */
namespace Tk\Auth\Adapter;
use Tk\Auth\Result;

/**
 * Digest Authentication adapter
 *
 * This object uses a .htpasswd file or similar generated by the apache tools.
 * 
 * Config options:
 *
 *   $config['system.auth.digest.file']    = '/home/user/.htpasswd';
 *   $config['system.auth.digest.realm']    = '';
 *   $config['system.auth.digest.scheme']    = 'basic';
 *
 * 
 * 
 * @link https://en.wikipedia.org/wiki/Digest_access_authentication
 * @todo THis needs tpo be checked, this code will not work securely.
 */
class Digest extends Iface
{
    /**
     * @var string
     */
    protected $scheme = 'basic';
    
    /**
     * @var string
     */
    protected $realm = '';

    /**
     * Full path to the digest password file
     * @var string
     */
    protected $file = '';


    /**
     * Constructor
     *
     * @param string $file
     * @param string $realm
     * @param $scheme
     * @throws \Tk\Auth\Exception
     */
    public function __construct($file, $realm, $scheme)
    {
        throw new \Tk\Auth\Exception('This ain`t working yet, fix it!');
                
        $this->file = $file;
        $this->scheme = $scheme;
        $this->realm = $realm;
        
        if (!is_file($this->file)) {
            throw new \Tk\Auth\Exception('Cannot locate digest file: ' . $this->file);
        }
    }


    /**
     * Defined by Tk\Auth\Adapter\Iface
     *
     * @throws \Tk\Auth\Exception
     * @return \Tk\Auth\Result
     */
    public function authenticate()
    {
        if (false === ($fileHandle = @fopen($this->getDigestFile(), 'r'))) {
            return new Result(Result::FAILURE, $this->getUsername(), 'System authentication error.');
        }
        $id = $this->getUsername() . ':' . $this->getRealm();
        $idLength = strlen($id);
        while ($line = trim(fgets($fileHandle))) {
            if (substr($line, 0, $idLength) === $id) {
                if ( $this->_secureStringCompare(substr($line, -32), self::hash(sprintf('%s:%s:%s', $this->getUsername(), $this->getRealm(), $this->getPassword()), 'md5')) ) { 
                    return new Result(Result::SUCCESS, $this->getUsername());
                } else {
                    return new Result(Result::FAILURE_CREDENTIAL_INVALID, $this->getUsername(), 'Username or Password incorrect');
                }
            }
        }
        return new Result(Result::FAILURE_IDENTITY_NOT_FOUND, $this->getUsername(), 'Invalid username or password.');
    }

    /**
     * Securely compare two strings for equality while avoided C level memcmp()
     * optimisations capable of leaking timing information useful to an attacker
     * attempting to iteratively guess the unknown string (e.g. password) being
     * compared against.
     *
     * @param string $a
     * @param string $b
     * @return bool
     */
    protected function _secureStringCompare($a, $b)
    {
        if (strlen($a) !== strlen($b)) {
            return false;
        }
        $result = 0;
        for ($i = 0; $i < strlen($a); $i++) {
            $result |= ord($a[$i]) ^ ord($b[$i]);
        }
        return $result == 0;
    }
}

